### ISSUE TITLE
z-index mixin

### ISSUE THREAD

**Issue by bnomei** [k-next/panel#92]
just found that z-index mixin, seems useful but repo does not use it often yet. care to explain what it will improve exactly?

https://github.com/k-next/ui/blob/master/styles/shared.scss#L17

**Comment by nocksock** [comment]
It should be used more often, indeed! 

It makes managing z-index easier. 

``` scss
.something-in-background {
  position: absolute;
  // […]
  z-index: z-index(background);
}
```

So you don't have to deal with numbers etc. The second parameter makes it possible to manage it within a component. Eg: `z-index(background, 1)`, will be one above `background`.
